In [2]:
import numpy as np
import scipy
from scipy import linalg

In [26]:
a = np.array([1, 1, 1, 0])[:, np.newaxis]
b = linalg.pinv(a)

In [32]:
np.outer(a, a)

array([[1, 1, 1, 0],
       [1, 1, 1, 0],
       [1, 1, 1, 0],
       [0, 0, 0, 0]])

In [23]:
b @ a

array([[0.33333333, 0.33333333, 0.33333333, 0.        ],
       [0.33333333, 0.33333333, 0.33333333, 0.        ],
       [0.33333333, 0.33333333, 0.33333333, 0.        ],
       [0.        , 0.        , 0.        , 0.        ]])

In [13]:
b

array([[0.25],
       [0.25],
       [0.25],
       [0.25]])